// <auto-generated />
using ApiVideos.Application.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiVideos.Application.Migrations
{
    [DbContext(typeof(ApiVideosContext))]
    [Migration("20250728120503_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ApiVideos.Application.Entities.Categorias.CategoriaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Cor = "Azul",
                            Titulo = "Livre"
                        },
                        new
                        {
                            Id = 2L,
                            Cor = "Vermelho",
                            Titulo = "Terror"
                        });
                });

            modelBuilder.Entity("ApiVideos.Application.Entities.Usuario.UsuarioEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "admin@admin.com",
                            Senha = "admin"
                        });
                });

            modelBuilder.Entity("ApiVideos.Application.Entities.Videos.VideoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoriaId = 1L,
                            Descricao = "Madrugada com gente morta",
                            Titulo = "Madrugada dos Mortos",
                            Url = "http://madrugadadosmortos.com.br"
                        },
                        new
                        {
                            Id = 2L,
                            CategoriaId = 2L,
                            Descricao = "Parecem que foi mais nao voltaram",
                            Titulo = "A volta dos que nao foram",
                            Url = "http://fuievoltei.com.br"
                        });
                });

            modelBuilder.Entity("ApiVideos.Application.Entities.Videos.VideoEntity", b =>
                {
                    b.HasOne("ApiVideos.Application.Entities.Categorias.CategoriaEntity", "Categoria")
                        .WithMany("Videos")
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ApiVideos.Application.Entities.Categorias.CategoriaEntity", b =>
                {
                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
